language: ruby
before_script:
  - "sudo apt-get install -y ruby rubygems"
  - "sudo -i gem install json"
  - "sudo script/git_user/setup git $USER"
  - "mysql -e 'create database gitty_test;'"
  - "rake db:migrate"
rvm:
  - 1.9.2
  - 1.9.3
