language: ruby
before_script:
  - "sudo apt-get install -y ruby rubygems"
  - "sudo -i gem install json"
  - "sudo script/git_user/setup git $USER"
  - "mysql -e 'create database gitty_test;'"
  - "rake db:migrate"
  - "git config --global user.email tester@testing.com"
  - "git config --global user.name \"Testing Tester\""
rvm:
  - 1.9.3
  - 2.0.0
